// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function Index_page(props) {
  return JsxRuntime.jsxs(React.Fragment, {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Rick and Morty characters",
                      className: "text-3xl"
                    }),
                JsxRuntime.jsx("p", {
                      children: "Please use the sidebar to learn more about your favorite characters.",
                      className: "mt-2"
                    }),
                JsxRuntime.jsx("hr", {}),
                JsxRuntime.jsxs("p", {
                      children: [
                        "This is a demo application created using ",
                        JsxRuntime.jsx("a", {
                              children: "ReScript",
                              className: "underline text-blue-500 hover:text-blue-900",
                              title: "ReScript",
                              href: "https://rescript-lang.org/"
                            }),
                        ".",
                        JsxRuntime.jsx("a", {
                              children: JsxRuntime.jsx("img", {
                                    className: "w-10 mt-5",
                                    alt: "GitHub repository",
                                    src: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
                                  }),
                              title: "GitHub repo",
                              href: "https://github.com/jderochervlk/rescript-vike-relay"
                            })
                      ],
                      className: "text-l mt-5"
                    })
              ]
            });
}

var make = Index_page;

export {
  make ,
}
/* react Not a pure module */
