// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Counter from "./Counter.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Page() {
  return JsxRuntime.jsxs(React.Fragment, {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Welcome"
                    }),
                "This page is:",
                JsxRuntime.jsxs("ul", {
                      children: [
                        JsxRuntime.jsx("li", {
                              children: "Rendered to HTML."
                            }),
                        JsxRuntime.jsxs("li", {
                              children: [
                                "Interactive ",
                                JsxRuntime.jsx(Counter.make, {})
                              ]
                            })
                      ]
                    })
              ]
            });
}

export {
  Page ,
}
/* react Not a pure module */
