// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function Error_page(props) {
  if (props.is404) {
    return JsxRuntime.jsxs(React.Fragment, {
                children: [
                  JsxRuntime.jsx("h1", {
                        children: "404 Page Not Found"
                      }),
                  JsxRuntime.jsx("p", {
                        children: "This page could not be found."
                      })
                ]
              });
  } else {
    return JsxRuntime.jsxs(React.Fragment, {
                children: [
                  JsxRuntime.jsx("h1", {
                        children: "500 Internal Error"
                      }),
                  JsxRuntime.jsx("p", {
                        children: "Something went wrong."
                      })
                ]
              });
  }
}

var make = Error_page;

export {
  make ,
}
/* react Not a pure module */
