// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as Router from "vike/client/router";

function Link(props) {
  var to = props.to;
  var onClick = function (param) {
    Router.navigate(to);
  };
  return JsxRuntime.jsx("a", {
              children: props.children,
              className: props.className,
              style: {
                cursor: "pointer"
              },
              onClick: onClick
            });
}

var make = Link;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
