// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PageState from "./pageState.mjs";
import * as PageContext from "./pageContext.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Link(props) {
  var href = props.href;
  var context = PageContext.usePageContext(undefined);
  console.log(context);
  var match = PageState.useAtom(undefined);
  var url = match[0]["urlOriginal"];
  console.log(400, url, href, false);
  return JsxRuntime.jsx("a", {
              children: props.children,
              className: props.className,
              style: {
                cursor: "pointer"
              },
              href: href
            });
}

var make = Link;

export {
  make ,
}
/* PageState Not a pure module */
