// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as PageContext$MyRescriptViteApp from "../src/pageContext.mjs";

function Link(props) {
  var context = PageContext$MyRescriptViteApp.usePageContext(undefined);
  console.log(context);
  return JsxRuntime.jsx("a", {
              children: props.children,
              className: props.className,
              style: {
                cursor: "pointer"
              },
              href: props.href
            });
}

var make = Link;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
