// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

var context = React.createContext(undefined);

var t = context.Provider;

function PageContext$Provider(props) {
  var pageContext = props.pageContext;
  console.log(202, pageContext);
  return JsxRuntime.jsx("t", {
              children: props.children,
              value: pageContext
            });
}

var Provider = {
  t: t,
  make: PageContext$Provider
};

function usePageContext() {
  return React.useContext(context);
}

var empty;

export {
  empty ,
  context ,
  Provider ,
  usePageContext ,
}
/* context Not a pure module */
