// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jotai from "jotai";

var pageAtom = Jotai.atom({
      "": ""
    });

function useAtom() {
  return Jotai.useAtom(pageAtom);
}

export {
  pageAtom ,
  useAtom ,
}
/* pageAtom Not a pure module */
