// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

var context = React.createContext(0);

var t = context.Provider;

function PageContext$Provider(props) {
  return JsxRuntime.jsx("t", {
              children: props.children,
              value: props.pageContext
            });
}

var Provider = {
  t: t,
  make: PageContext$Provider
};

function usePageContext() {
  return React.useContext(context);
}

export {
  context ,
  Provider ,
  usePageContext ,
}
/* context Not a pure module */
