// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RescriptRelay from "rescript-relay/src/RescriptRelay.mjs";
import * as RelayRuntime from "relay-runtime";
import * as RelayNetwork from "./relayNetwork";

function makeNetwork(prim) {
  return RelayNetwork.makeNetwork(prim);
}

var source = new RelayRuntime.RecordSource(undefined);

var store = RescriptRelay.Store.make(source, 10, undefined, undefined);

function makeEnvironment(relayServerSSR) {
  return RescriptRelay.Environment.make(RelayNetwork.makeNetwork(relayServerSSR), store, undefined, undefined, undefined, undefined, undefined, undefined);
}

export {
  makeNetwork ,
  source ,
  store ,
  makeEnvironment ,
}
/* source Not a pure module */
