// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as Character$MyRescriptViteApp from "../../src/Character.mjs";

import './code.css'
;

function About_page$Content(props) {
  var t = Character$MyRescriptViteApp.ListQuery.use(undefined, undefined, undefined, undefined, undefined);
  var results = Core__Option.flatMap(t.characters, (function (t) {
          return t.results;
        }));
  if (results !== undefined) {
    return results.map(function (c) {
                if (c === undefined) {
                  return null;
                }
                var id = Core__Option.getWithDefault(c.id, "-");
                return JsxRuntime.jsx(Character$MyRescriptViteApp.make, {
                            id: id
                          }, "character-details-" + id);
              });
  } else {
    return [];
  }
}

var Content = {
  make: About_page$Content
};

function About_page(props) {
  return JsxRuntime.jsxs(React.Fragment, {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "About"
                    }),
                JsxRuntime.jsx(React.Suspense, {
                      children: Caml_option.some(JsxRuntime.jsx(About_page$Content, {}))
                    })
              ]
            });
}

var make = About_page;

export {
  Content ,
  make ,
}
/*  Not a pure module */
