// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as Character$MyRescriptViteApp from "../../src/Character.mjs";

import './code.css'
;

function About_page(props) {
  var t = Character$MyRescriptViteApp.ListQuery.use(undefined, undefined, undefined, undefined, undefined);
  var results = Core__Option.flatMap(t.characters, (function (t) {
          return t.results;
        }));
  return JsxRuntime.jsxs(React.Fragment, {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "About"
                    }),
                JsxRuntime.jsx(React.Suspense, {
                      children: results !== undefined ? results.map(function (c) {
                              if (c !== undefined) {
                                return JsxRuntime.jsx(Character$MyRescriptViteApp.make, {
                                            id: Core__Option.getWithDefault(c.id, "")
                                          });
                              } else {
                                return null;
                              }
                            }) : []
                    })
              ]
            });
}

var make = About_page;

export {
  make ,
}
/*  Not a pure module */
