// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

var context = React.createContext(undefined);

var p = context.Provider;

function PageContext$Provider(props) {
  return JsxRuntime.jsx("p", {
              children: props.children,
              value: props.pageContext
            });
}

var Provider = {
  p: p,
  make: PageContext$Provider
};

function usePageContext(param) {
  return React.useContext(context);
}

var empty;

export {
  empty ,
  context ,
  Provider ,
  usePageContext ,
}
/* context Not a pure module */
