// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as Character$MyRescriptViteApp from "../../../src/Character.mjs";

function Character_page(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(React.Suspense, {
                    children: Caml_option.some(JsxRuntime.jsx(Character$MyRescriptViteApp.make, {
                              id: props.routeParams.id
                            }))
                  })
            });
}

var make = Character_page;

export {
  make ,
}
/* react Not a pure module */
